version: "3.9"
volumes:
  magische-db-data:
services:
  app:
    container_name: magische_app
    image: magische
    build:
      args:
        - target=deploy
    env_file:
      - .env
    volumes:
      - .:/app
    ports:
      - ${APP_CLIENT_PORT:-80}:${PORT}
    healthcheck:
      test: ["CMD", "./healthcheck"]
      interval: 5s
      timeout: 10s
      retries: 10
      start_period: 5s
    depends_on:
      db:
        condition: service_healthy
  db:
    image: mysql:8.0
    container_name: magische-db
    env_file:
      - .env
    volumes:
      - magische-db-data:/var/lib/mysql
      - ./db/conf.d:/etc/mysql/conf.d:cached
    ports:
      - "${MYSQL_CLIENT_PORT:-3306}:3306"
    healthcheck:
      test: mysqladmin ping -u${MYSQL_USER} -p${MYSQL_PASSWORD}
      interval: 2s
      timeout: 1s
      retries: 100
      start_period: 1s
