name: Build and Push Docker Image

on:
  push:
    branches:
      - develop

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      - name: Prepare
        id: prep
        run: |
          echo ::set-output name=date::$(date +%Y%m%d)
          echo ::set-output name=sha::$(echo ${GITHUB_SHA} | cut -c1-8)

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - uses: docker/metadata-action@v5
        id: meta
        with:
          images: ghcr.io/${{ github.repository }}/server
          tags: |
            type=sha,format=long,prefix=
            type=raw,value=latest
            type=raw,value=build-${{ steps.prep.outputs.date }}-${{ steps.prep.outputs.sha }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          cache-from: type=gha
          cache-to: type=gha,mode=max
          file: ./Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          target: deploy
